language: python
# command to install dependencies
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install --user -r requirements.txt --use-feature=2020-resolver
# command to run tests
script: echo foo
#script:
  #- pytest
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  #- find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
